### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by JasonHK** [JasonHK-HKCC/SEHH2042-Group-Project#1]
# Project Requirements

- [x] R0: Welcome message and the menu
- [x] R1: Add an assignment (@Rsdtdt)
- [x] R2: Delete an assignment (@humblehins)
- [x] R3: Add assignments in batch (@JasonHK)
- [x] R4: Show latest seating plan (@reg17971)
- [x] R5: Show details (@benyip303)
- [x] R6: Exit
